from __future__ import annotations

import html
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from examples.in_car_restaurant_agent import run_scenario  # noqa: E402


SCENARIOS = [
    "happy_path",
    "fallback_restaurant",
    "reservation_retry",
    "user_rejects",
    "location_denied",
]


def main() -> None:
    output = ROOT / "examples" / "in_car_restaurant_agent" / "artifacts"
    traces = output / "traces"
    traces.mkdir(parents=True, exist_ok=True)
    results = []
    timelines = {}
    for scenario in SCENARIOS:
        result, trace = run_scenario(scenario, traces / f"{scenario}.jsonl")
        results.append(result)
        timelines[scenario] = trace.events

    (output / "summary.json").write_text(
        json.dumps(results, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (output / "summary.md").write_text(render_markdown(results), encoding="utf-8")
    (output / "week-one-results.svg").write_text(render_results_svg(results), encoding="utf-8")
    (output / "happy-path-timeline.svg").write_text(
        render_timeline_svg(timelines["happy_path"]),
        encoding="utf-8",
    )
    print(json.dumps(results, ensure_ascii=False, indent=2))


def render_markdown(results: list[dict]) -> str:
    rows = [
        "# Week-one sandbox results",
        "",
        "These values were generated by executing the runtime, not entered by hand.",
        "All restaurant, location, route, confirmation, and reservation data is synthetic.",
        "",
        "| Scenario | Status | Completed | Reserved | Navigated | Tool calls | Retries | Duration |",
        "|---|---|---:|---:|---:|---:|---:|---:|",
    ]
    for result in results:
        rows.append(
            "| {scenario} | {status} | {task_completed} | {reservation_created} | "
            "{navigation_started} | {tool_calls} | {retries} | {total_duration_ms} ms |".format(**result)
        )
    return "\n".join(rows) + "\n"


def render_results_svg(results: list[dict]) -> str:
    width, row_height = 940, 58
    height = 120 + row_height * len(results)
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" rx="18" fill="#0d1117"/>',
        '<style>text{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.h{fill:#f0f6fc;font-size:24px;font-weight:700}.s{fill:#8b949e;font-size:13px}.n{fill:#f0f6fc;font-size:15px}.v{fill:#58a6ff;font-size:15px;font-weight:700}</style>',
        '<text x="34" y="42" class="h">Vehicle agent · week-one evidence</text>',
        '<text x="34" y="68" class="s">Five real sandbox executions · Trace Schema v0.1.0</text>',
        '<text x="34" y="102" class="s">SCENARIO</text><text x="390" y="102" class="s">STATUS</text><text x="520" y="102" class="s">TOOLS</text><text x="620" y="102" class="s">RETRIES</text><text x="735" y="102" class="s">DURATION</text>',
    ]
    colors = {"success": "#3fb950", "cancelled": "#d29922", "needs_input": "#a371f7", "failed": "#f85149"}
    for index, result in enumerate(results):
        y = 130 + index * row_height
        parts.append(f'<line x1="34" y1="{y-18}" x2="906" y2="{y-18}" stroke="#21262d"/>')
        parts.append(f'<text x="34" y="{y+13}" class="n">{html.escape(result["scenario"])}</text>')
        color = colors[result["status"]]
        parts.append(f'<circle cx="398" cy="{y+8}" r="6" fill="{color}"/>')
        parts.append(f'<text x="414" y="{y+13}" class="n">{html.escape(result["status"])}</text>')
        parts.append(f'<text x="520" y="{y+13}" class="v">{result["tool_calls"]}</text>')
        parts.append(f'<text x="620" y="{y+13}" class="v">{result["retries"]}</text>')
        parts.append(f'<text x="735" y="{y+13}" class="v">{result["total_duration_ms"]} ms</text>')
    parts.append('</svg>')
    return "".join(parts)


def render_timeline_svg(events: list[dict]) -> str:
    completed = [event for event in events if event["event_type"] == "tool.call.completed"]
    width, height = 940, 120 + 54 * len(completed)
    max_duration = max(event["duration_ms"] for event in completed) or 1
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" rx="18" fill="#ffffff"/>',
        '<style>text{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.h{fill:#17202a;font-size:24px;font-weight:700}.s{fill:#667085;font-size:13px}.n{fill:#344054;font-size:14px}.v{fill:#175cd3;font-size:13px;font-weight:700}</style>',
        '<text x="34" y="42" class="h">Happy path · tool timeline</text>',
        '<text x="34" y="68" class="s">Measured wall-clock duration for each completed sandbox tool call</text>',
    ]
    for index, event in enumerate(completed):
        y = 106 + index * 54
        bar_width = max(8, round(470 * event["duration_ms"] / max_duration))
        parts.append(f'<text x="34" y="{y+15}" class="n">{html.escape(event["component"])}</text>')
        parts.append(f'<rect x="280" y="{y}" width="{bar_width}" height="22" rx="6" fill="#2e90fa" opacity="0.88"/>')
        parts.append(f'<text x="{295+bar_width}" y="{y+16}" class="v">{event["duration_ms"]} ms</text>')
    parts.append('</svg>')
    return "".join(parts)


if __name__ == "__main__":
    main()
